before:
  hooks:
    - go mod tidy
    - go generate ./...
dist: keyexchange
builds:
  - dir: cmd
    env:
      - CGO_ENABLED=0
    goos:
      - "darwin"
      - "dragonfly"
      - "freebsd"
      - "illumos"
      - "linux"
      - "netbsd"
      - "openbsd"
      - "solaris"
      - "windows"
    goarch:
      - "amd64"
      - "386"
      - "arm"
      - "arm64"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
