include: package:flutter_lints/flutter.yaml
# include: package:lints/recommended.yaml
# include: package:pedantic/analysis_options.1.11.0.yaml
# include: package:effective_dart/analysis_options.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - cancel_subscriptions