version: 3

tasks:
  flutter:
    cmds:
      - cmd: flutter run -d windows

  go:
    cmds:
      - cmd: go build -buildmode=c-shared -o taskwire/lib.so ./taskwire
      - cmd: go build -buildmode=c-shared -o taskwire/lib.dll ./taskwire
      - cmd: go build -buildmode=c-shared -o taskwire/lib.dylib ./taskwire

  sshtest:
    cmds:
      - cmd: podman rm -f sshdummy
        ignore_error: true
      - cmd: podman build --build-arg PASSWORD=taskwire -t sshdummy -f test/ssh/Dockerfile .
      - cmd: podman run --name sshdummy -d -p 2222:22 sshdummy