version: 3

tasks:
  flutter:
    cmds:
      - cmd: flutter run -d windows

  go:
    cmds:
      - cmd: go build -buildmode=c-shared -o taskwire/lib.so ./taskwire
      - cmd: go build -buildmode=c-shared -o taskwire/lib.dll ./taskwire
      - cmd: go build -buildmode=c-shared -o taskwire/lib.dylib ./taskwire

  sshtest:
    cmds:
      - task: _sshtest
        vars:
          OS: alpine
          PORT: "2201"
      - task: _sshtest
        vars:
          OS: fedora
          PORT: "2202"
      - task: _sshtest
        vars:
          OS: ubuntu
          PORT: "2203"

  _sshtest:
    cmds:
      - cmd: podman rm -f sshdummy{{.OS}}
        ignore_error: true
      - cmd: podman build --build-arg PASSWORD=taskwire -t sshdummy{{.OS}} -f test/ssh/{{.OS}}.dockerfile .
      - cmd: podman run --name sshdummy{{.OS}} -d -p {{.PORT}}:22 sshdummy{{.OS}}
  
  buildgo:
    cmds:
      - rm -fr keyexchange
      - goreleaser build --snapshot